day40_MovieProject_后台实现/app/home/forms.py
"""
文件名: forms.py
日期: 2019-03-17  
作者: lvah
联系: xc_guofan@qq.com
代码描述: 



"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField
from wtforms.validators import DataRequired, Length, EqualTo, Email, Regexp
from flask_wtf.file import  FileAllowed

class BaseForm(FlaskForm):
    username = StringField(
        label="用户名",
        validators=[
            DataRequired()

        ]
    )
    password = PasswordField(
        label="密码",
        validators=[
            DataRequired(),
            Length(6, 12, message="密码长度必须为6-12")

        ]
    )


class LoginForm(BaseForm):
    submit = SubmitField(
        label="登录"
    )

class RegisterForm(BaseForm):
    repassword = PasswordField(
        label="确认密码",
        validators=[
            EqualTo('password', message="两次密码不一致")
        ]
    )
    email = StringField(
        label="邮箱",
        validators=[
            Email(message="邮箱格式不正确")
        ]
    )

    submit = SubmitField(
        label="注册"
    )


class EditUserForm(FlaskForm):
    username = StringField(
        label="用户名",
        validators=[
            DataRequired()

        ]
    )
    email = StringField(
        label="邮箱",
        # validators=[
        #     Email(message="邮箱格式不正确")
        # ]
    )

    phone = StringField(
        label="电话",
        # validators=[
        #     Regexp(r'1\d{10}', message="电话号码格式不正确")
        # ]
    )
    face = FileField(
        label="用户头像",
        validators=[
            # *******限制用户上传文件的格式
            FileAllowed(['png', 'jpg'], message="用户头像格式错误， 必须为png或者jpg")

        ]
    )

    info = TextAreaField(
        label="用户简介",
    )

    submit = SubmitField(
        label="更新信息"
    )



class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label="旧密码",
        validators=[
            DataRequired()
        ],
    # <input name="xxx" placeholder="">
    render_kw = {
        'placeholder' : "请输入旧密码"
    }
    )
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired()
        ],
        render_kw={
            'placeholder': "请输入新密码"
        }
    )

    submit = SubmitField(
        label="修改密码"
    )

day40_MovieProject_后台实现/app/admin/views/comment.py
"""
文件名: comment.py
日期: 2019-03-24  
作者: lvah
联系: xc_guofan@qq.com
代码描述: 



"""

from app import app, db
from flask import render_template, flash, redirect, url_for, request
from app.admin import admin
from app.admin.utils import write_adminlog, is_admin_login
from app.models import User, Comment


# ***************************评论管理*****************************
@admin.route("/comment/list/")
@admin.route("/comment/list/<int:page>/")
@is_admin_login
def comment_list(page=1):
    commentsPageObj = Comment.query.paginate(page, per_page=app.config['PER_PAGE'])
    return render_template('admin/comment/list.html', commentsPageObj=commentsPageObj)


@admin.route("/comment/delete/<int:id>/")
@is_admin_login
def comment_delete(id=None):
    if id:
        comment = Comment.query.get_or_404(id)
        db.session.delete(comment)
        db.session.commit()
        flash('删除%s用户%s电影评论成功！' % (comment.user.name, comment.movie.name), category='ok')
        write_adminlog('删除%s用户%s电影评论成功！' % (comment.user.name, comment.movie.name))
        return redirect(url_for('admin.comment_list', page=1))

day40_MovieProject_后台实现/app/admin/views/user.py
"""
文件名: user.py
日期: 2019-03-24  
作者: lvah
联系: xc_guofan@qq.com
代码描述: 



"""

import os

from werkzeug.utils import secure_filename

from app import app, db
from flask import render_template, flash, redirect, url_for, request
from app.admin import admin
from app.admin.utils import write_adminlog, is_admin_login
from app.models import User


@admin.route("/user/list/")
@admin.route("/user/list/<int:page>/")
@is_admin_login

def user_list(page=1):
    usersPageObj = User.query.paginate(page=page, per_page=app.config['PER_PAGE'])
    return render_template('admin/user/list.html', usersPageObj=usersPageObj, app=app)


@admin.route("/user/view/<int:user_id>/")
@is_admin_login
def user_view(user_id=None):
    if user_id:
        user = User.query.get_or_404(user_id)
        return render_template('admin/user/view.html',
                               user=user,
                               app=app)


@admin.route("/user/delete/<int:id>/")
@is_admin_login
def user_del(id=None):
    if id:
        user = User.query.get_or_404(id)
        # 删除同时要从磁盘中删除封面文件
        file_save_path = app.config['FC_DIR']  # 头像上传保存路径
        # 如果存在将进行删除，不判断，如果文件不存在删除会报错
        if os.path.exists(os.path.join(file_save_path, user.face)):
            os.remove(os.path.join(file_save_path, user.face))

        # 删除数据库，提交修改
        db.session.delete(user)
        db.session.commit()
        # 删除后闪现消息
        flash('删除会员%s成功！' % (user.name), category='ok')
        write_adminlog('删除会员%s成功！' % (user.name))
        return redirect(url_for('admin.user_list', page=1))

day40_MovieProject_后台实现/app/home/__init__.py
from flask import  Blueprint


# 定义蓝图
home = Blueprint("home", __name__)

from app.home.views import  *

day40_MovieProject_后台实现/app/home/views.py
"""
文件名: views.py
日期: 2019-03-17  
作者: lvah
联系: xc_guofan@qq.com
代码描述: 



"""
# 导入home的蓝图对象
import json
import os

import requests

from app import db, app
from app.home.forms import LoginForm, RegisterForm, EditUserForm, PwdForm
from app.home.utils import is_login, change_filename
from app.models import User, Comment, Userlog, MovieCollect, Movie, Preview

from . import home
from flask import render_template, flash, session, redirect, url_for, request
from werkzeug.security import generate_password_hash


@home.route('/')
@home.route('/<int:page>/')
def index(page=1):
    page_movies = Movie.query.paginate(page, per_page=app.config['PER_PAGE'])
    previews = Preview.query.all()
    return render_template('home/index.html',
                           page_movies=page_movies,
                           app=app,
                           previews=previews)


# 注册页面
@home.route('/register/', methods=['POST', 'GET'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # 1. 从前端获取用户输入的值;
        email = form.email.data
        username = form.username.data
        password = form.password.data

        # 2. 判断用户是否已经存在? 如果返回位None，说明可以注册;
        u = User.query.filter_by(name=username).first()
        if u:
            flash("用户%s已经存在" % (u.name))
            return redirect(url_for('home.register'))
        else:
            u = User(name=username, email=email)
            u.password = generate_password_hash(password)  # 对于密码进行加密
            db.session.add(u)
            db.session.commit()
            flash("注册用户%s成功" % (u.name))
            return redirect(url_for('home.login'))
    return render_template('home/register.html',
                           form=form)


@home.route('/login/', methods=['POST', 'GET'])
def login():
    from app.models import User, Userlog
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(name=username).first()
        if user and user.verify_password(password):
            # session信息的保存
            session['user_id'] = user.id
            session['user'] = user.name
            flash("用户%s登录成功" % (user.name))
            remote_ip = request.remote_addr
            # 将登录信息写到日志中;
            userlog = Userlog(user_id=user.id,
                              ip=remote_ip,
                              area='xxx内网IP')
            db.session.add(userlog)
            db.session.commit()

            # 从index蓝图里面寻找index函数;
            return redirect(url_for('home.user'))
        else:
            flash("用户登录失败")
            return redirect(url_for('home.login'))
    return render_template('home/login.html',
                           form=form)


@home.route('/logout/')
@is_login
def logout():
    session.pop('user_id', None)
    session.pop('user', None)

    return redirect(url_for('home.login'))


@home.route('/user/', methods=['GET', 'POST'])
@is_login
def user():
    form = EditUserForm()
    # 先在页面表单显示用户已经填写的信息
    user = User.query.filter_by(name=session.get('user')).first()
    form.username.data = user.name
    form.email.data = user.email
    form.phone.data = user.phone
    if form.validate_on_submit():
        # request.form   - 获取表单填写的内容
        username = request.form['username']
        email = request.form['email']
        phone = request.form['phone']
        info = request.form['info']
        # 1. 判断更改的用户名是否已经存在;  --- 邮箱和电话自己判断, 此处省略
        if username != user.name and \
                User.query.filter_by(name=username).count():
            flash("用户名%s已经存在" % (username))
            return redirect(url_for('home.user'))

        if User.query.filter_by(email=email).count() and \
                email != user.email:
            flash("邮箱%s已经注册" % (email))
            return redirect(url_for('home.user'))

        #  保存更改的信息到数据库中;(难点： 存储用户头像)
        #  *****存储用户的头像;
        file_save_path = app.config['FC_DIR']
        if not os.path.exists(file_save_path):
            os.makedirs(file_save_path)
        # 判断是否上传了新的头像;
        if form.face.data:
            # 判断之前是否已经有用户头像， 如果有， 则删除;
            if user.face and os.path.exists(os.path.join(file_save_path, user.face)):
                print(user.face)
                os.remove(os.path.join(file_save_path, user.face))  # 删除旧头像

            # 保存新的头像， 获取用户头像文件的文件名
            face_name = form.face.data.filename
            face_name = change_filename(face_name)
            print(face_name)
            # 保存新的头像文件
            form.face.data.save(os.path.join(file_save_path, face_name))
            user.face = face_name

        user.name = username
        user.email = email
        user.phone = phone
        user.info = info

        db.session.add(user)
        db.session.commit()
        flash("修改会员信息成功")
        # ******修改用户信息， 如果修改的是用户名， 一定要登录出， 再重新登录。
        logout()
        return redirect(url_for('home.login'))
    return render_template('home/user.html',
                           form=form)


# 修改密码
@home.route('/pwd/', methods=['GET', 'POST'])
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        # 获取当前登录用户的密码
        user = User.query.filter_by(name=session.get('user')).first()
        print(session.get('name'))
        # 判断用户的旧密码是否正确
        if user.verify_password(form.old_pwd.data):
            # ********数据库里面的是password
            user.password = generate_password_hash(form.new_pwd.data)
            db.session.add(user)
            db.session.commit()
            flash("密码更新成功")
        else:
            flash("旧密码错误, 请重新输入")
        return redirect(url_for('home.pwd'))
    return render_template('home/pwd.html', form=form)


@home.route('/comments/')
@home.route('/comments/<int:page>/')
def comments(page=1):
    commentsPageObj = Comment.query.filter_by(user_id=session.get('user_id')
                                              ).paginate(page, per_page=app.config['PER_PAGE'])
    return render_template('home/comments.html',
                           commentsPageObj=commentsPageObj)


# 记录用户登录日志
@home.route('/userlog/')
@home.route('/userlog/<int:page>/')
def userlog(page=1):
    userlogsPageObj = Userlog.query.filter_by(user_id=session.get('user_id')
                                    ).paginate(page, per_page=app.config['PER_PAGE'])

    return render_template('home/userlog.html',
                           userlogsPageObj=userlogsPageObj)


@home.route('/moviecollect/')
@home.route('/moviecollect/<int:page>/')
def moviecollect(page=1):
    moviecollectsPageObj = MovieCollect.query.filter_by(user_id = session.get('user_id')
                                 ).paginate(page, per_page=app.config['PER_PAGE'])
    return render_template('home/moviecollect.html',
                           moviecollectsPageObj=moviecollectsPageObj
                           )



@home.route('/play/<int:id>')
def play(id):
    return  render_template('home/play.html')

day40_MovieProject_后台实现/app/templates/home/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
    {#  先继承父类的css样式导入   #}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}


{% block scripts %}

    {{ super() }}
    {#    实质使导入moment.js库的, 通过Flask-moment集成了起来#}
    {{ moment.include_moment() }}
    <script src="{{ url_for('static', filename='js/echarts.min.js') }}"></script>

{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">微电影网站</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                <ul class="nav navbar-nav navbar-right">
                    {#       分类讨论:
                            1. 如果没有登录， 显示登录和注册按钮；
                            2. 如果登录成功， 显示用户名称和注销按钮

            #}

                <li><a href="#">电影</a></li>
                    {% if not session.user %}
                        <li><a href="{{ url_for('home.login') }}">登录</a></li>
                        <li><a href="{{ url_for('home.register') }}">注册</a></li>
                    {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">当前用户：{{ session.user }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for('home.logout') }}">注销</a></li>
                            </ul>
                        </li>

                    {% endif %}
                </ul>


            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>


    {#让每个页面都可以获取闪现信息闪现#}
    {% for item in get_flashed_messages() %}

        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            {{ item }}
        </div>
    {% endfor %}
{% endblock %}

day40_MovieProject_后台实现/app/templates/home/comments.html
{% extends 'home/base.html' %}
{#
参考代码:
    bootstrap媒体对象: https://v3.bootcss.com/components/#panels
    bootstrap面板对象: https://v3.bootcss.com/components/#panels-heading

#}

{% block scripts %}
    {{ super() }}
    <script>
        $(document).ready(function () {
            $("#md-3").addClass('active');
        });
    </script>
{% endblock %}
{% block content %}
    <div class="container-fluid">

        {% include 'home/usermenu.html' %}

        <div class="col-md-9">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-map-marker"></span>
                        &nbsp;评论记录</h3>
                </div>
                <div class="panel-body">
                    {% for i in range(10) %}
                        <ul class="media-list">
                            <li class="media">
                                <div class="media-right">
                                    <a href="#">
                                        <img class="media-object"
                                             src="/static/upload/userFaceImg/20190323_11270930ca91ef76c6a7ef6e9494def1faaf51f1de66f7.jpg"
                                             alt="..."

                                             style="width: 60px; height: 60px">
                                    </a>
                                </div>
                                <div class="media-body">

                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            westos评论xxxx电影于2019-10-12 23:00:00
                                        </div>
                                        <div class="panel-body">
                                            评论的内容
                                        </div>
                                    </div>

                            </li>
                        </ul>

                    {% endfor %}

                    <div class="col-md-12 text-center">
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                <li>
                                    <a href="#" aria-label="First">
                                        <span aria-hidden="true">首页</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">上一页</span>
                                    </a>
                                </li>
                                <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                                <li>
                                    <a href="#" aria-label="Next">
                                        <span aria-hidden="true">下一页</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" aria-label="Last">
                                        <span aria-hidden="true">尾页</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

day40_MovieProject_后台实现/app/templates/home/index.html
{% extends 'home/base.html' %}
{#
1. 轮播图:http://www.runoob.com/try/try.php?filename=bootstrap3-plugin-carousal-caption
2. 各种选择标签
3. 相关电影: https://v3.bootcss.com/components/#thumbnails-custom-content
#}
{% block title %}首页{% endblock %}
{% block content %}






    <div class="container-fluid">
        <div class="col-lg-10 col-lg-offset-1">
            {#   轮播图   #}
            <div id="myCarousel" class="carousel slide">
                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    {% for preview in previews %}
                        {% if loop.first %}
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        {% else %}
                            <li data-target="#myCarousel" data-slide-to="{{ loop.index0 }}"></li>
                        {% endif %}
                    {% endfor %}
                </ol>
                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner">
                    {#                 #}
                    {% for preview in previews %}

                        {% if loop.first %}
                            <div class="item active">
                                <img src="{{ url_for('static', filename=app.config['PREVIEW_UP_DIR_LAST'] + preview.logo) }}"
                                     alt="First slide">
                                <div class="carousel-caption">{{ preview.name }}</div>
                            </div>
                        {% else %}
                            <div class="item">
                                <img src="{{ url_for('static', filename=app.config['PREVIEW_UP_DIR_LAST'] + preview.logo) }}"
                                     alt="Second slide">
                                <div class="carousel-caption">{{ preview.name }}</div>
                            </div>
                        {% endif %}
                    {% endfor %}

                </div>
                <!-- 轮播（Carousel）导航 -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            {#    各种选择标签   #}
            <table class="table text-left table-bordered" id="movietags">
                <tr>
                    <td style="width:10%;">电影标签</td>
                    <td style="width:80%;">
                        <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                        &nbsp;
                        <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                        &nbsp;
                        <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                        &nbsp;
                        <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                </tr>
                <tr>
                    <td>电影星级</td>
                    <td>

                        <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;二星</a>
                        &nbsp;
                        <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;三星</a>
                        &nbsp;
                        <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;四星</a>
                        &nbsp;
                        <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;五星</a>
                    </td>
                </tr>
                <tr>
                    <td>上映时间</td>
                    <td>


                        <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2017</span>
                        </a>
                        &nbsp;
                        <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2016</span>
                        </a>
                        &nbsp;
                        <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2015</span>
                        </a>
                        &nbsp;
                        <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;更早</span></a>
                    </td>
                </tr>
                <tr>
                    <td>播放数量</td>
                    <td>
                        <a class="label label-success"
                           href="#"
                        ><span
                                class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</a>
                        &nbsp;
                        <a class="label label-danger"
                           href="#"><span
                                class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</a>
                    </td>
                </tr>
                <tr>
                    <td>评论数量</td>
                    <td>
                        <a class="label label-success"
                           href="#"
                        ><span
                                class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</a>
                        &nbsp;
                        <a class="label label-danger"
                           href="#"
                        ><span
                                class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</a>
                    </td>
                </tr>
            </table>


            {#  电影列表信息           #}

            <div class="row">
                {% for movie in page_movies.items %}
                    <div class="col-sm-3 col-md-3">
                        <div class="thumbnail">
                            <img src="{{ url_for('static', filename=app.config['MOVIE_UP_DIR_LAST'] + movie.url) }}"
                                 alt="..." style="width: 240px; height: 330px">
                            <div class="caption">
                                <h3>{{ movie.name }}</h3>
                                <p>
                                    {{ movie.info }}
                                </p>

                                <div>
                                    <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                    <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                    <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                    <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                                    <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                                </div>

                                <a href="{{ url_for('home.play', id=movie.id) }}" class="btn btn-success btn-block" target="_blank" role="button">
                                    <span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                            </div>
                        </div>


                    </div>
                {% endfor %}
            </div>

            {#            分页显示  #}
            <div class="col-md-12 text-center">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>


        </div>

    </div>

{% endblock %}

day40_MovieProject_后台实现/app/templates/home/login.html
{% extends 'home/base.html' %}
{% import 'bootstrap/wtf.html'  as wtf %}


{% block title %}
    登录
{% endblock %}



{% block content %}
    <div class="container">
        <div class="col-lg-8 col-lg-offset-2">


            <div class="panel panel-success">
                <div class="panel-heading">
                    <h1 class="panel-title"><span class="glyphicon glyphicon-log-in">

                    </span>&nbsp;&nbsp;登录</h1>
                </div>
                <div class="panel-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>

        </div>


    </div>

{% endblock %}

day40_MovieProject_后台实现/app/templates/home/pwd.html
{% extends 'home/base.html' %}
{% import 'bootstrap/wtf.html'  as wtf %}

{% block title %}

    修改密码
{% endblock %}
{% block scripts %}
    {{ super() }}

    <script>
        $(document).ready(function () {
            $("#md-2").addClass('active');
        });
    </script>

{% endblock %}

{% block content %}

    <div class="container-fluid">

        {#  左侧菜单栏       #}
        {% include 'home/usermenu.html' %}


        {#  右侧用户中心       #}
        <div class="col-lg-9">
            {#   面板中心          #}
            <div class="panel panel-warning">
                {#   面板头部              #}
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
                    </h3>
                </div>
                {#   面板主体               #}
                <div class="panel-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>

        </div>
    </div>

{% endblock %}

day40_MovieProject_后台实现/app/templates/home/register.html
{% extends 'home/base.html' %}
{% import 'bootstrap/wtf.html'  as wtf %}


{% block title %}
    注册
{% endblock %}



{% block content %}
    <div class="container">
        <div class="col-lg-8 col-lg-offset-2">


            <div class="panel panel-success">
                <div class="panel-heading">
                    <h1 class="panel-title"><span class="glyphicon glyphicon-log-in">

                    </span>&nbsp;&nbsp;注册</h1>
                </div>
                <div class="panel-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>

        </div>


    </div>

{% endblock %}

day40_MovieProject_后台实现/app/templates/home/usermenu.html
<div class="col-lg-2">
<div class="list-group">
    <a href="{{ url_for('home.user') }}" class="list-group-item" id="md-1">
        <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
    </a>
    <a href="{{ url_for('home.pwd') }}" class="list-group-item" id="md-2">
        <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
    </a>
    <a href="{{ url_for('home.comments') }}" class="list-group-item" id="md-3">
        <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
    </a>
    <a href="{{ url_for('home.userlog') }}" class="list-group-item" id="md-4">
        <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
    </a>
    <a href="{{ url_for('home.moviecollect') }}" class="list-group-item" id="md-5">
        <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
    </a>
</div>
</div>